# app.py
from flask import Flask, render_template, jsonify
import requests
import os
import random

app = Flask(__name__)

# Diccionario de imágenes y descripciones
image_descriptions = {
    "static/images/2_4_4.png":  "Posición sexual SIRENA: Es difícil conocer a alguien que te satisfaga en la vida y en la cama, si has conseguido encontrar, apreciar lo que tienes, entregarte a él por completo, amar sin pedir compensación y satisfacer en todos los aspectos. El hombre se acuesta de espaldas con las piernas ligeramente dobladas por las rodillas y las separa ampliamente. La mujer se tumba encima de su pareja, las piernas están apretadas y ligeramente dobladas por las rodillas, con las manos se sujeta las pantorrillas y levanta un poco el cuerpo hacia las piernas, de manera que está sentada en el suelo. El hombre pone su mano en el pecho de su pareja femenina y lo acaricia durante el sexo.",
    "static/images/3_2_3.png": "Posición sexual  GATO: Incluso la posición más sencilla puede aportar una experiencia inolvidable a los socios, o viceversa, para ser otra marca en la lista de las variantes estudiadas, pero no es importante cómo, sino con quién, no te olvides de ello. La mujer se tumba de espaldas, sobre los codos levanta la parte superior de su cuerpo, las piernas están rectas, pero separadas. El hombre se acuesta sobre su compañera cara a cara, mantiene la parte superior del cuerpo sobre los brazos extendidos, las piernas están juntas y situadas entre las piernas de la compañera. Parece estar colgado sobre su dama y puede besar su cuello, sus labios en el proceso.",
    "static/images/4_1_3.png": " Posición sexual  BATIENTE: Necesitamos tener sexo no tanto para satisfacer nuestros deseos, sino para obtener placer, para llegar al éxtasis, entonces tu vida sexual no será rutinaria y aburrida. La mujer se pone de rodillas y se inclina completamente hacia delante, estirando los brazos por encima de la cabeza, dándoles forma de halo. El hombre se sitúa a la pareja femenina de tal manera, que sus nalgas se encuentran sobre los pies de la mujer, las piernas están muy separadas y la mujer se encuentra entre sus piernas. Las manos del hombre se echan hacia atrás, se ponen sobre sus manos y se hace el apoyo principal sobre ellas.",
    "static/images/barco.png": " Posición sexual  BARCO: Tocando cada centímetro de los cuerpos, se siente más profundamente y se siente más, se trabaja como un solo organismo, que se deja llevar por el deseo. La mujer se tumba cómodamente sobre el vientre, abre las piernas y levanta sexualmente la parte superior de su cuerpo, apoyándose con confianza en los codos. El hombre está encima, colocando sus piernas entre las de la pareja femenina apoyándose en sus rodillas y colgando sobre ella, apoyándose en sus manos que están a los lados de sus hombros. La pareja es libre de estar besándose el hombre tiene acceso a los hombros de su ama y por supuesto, los gemidos se mezclan con el aliento caliente.",
    "static/images/ahorcadas.png": "Posición sexual  AHORCADAS: La mujer encima es una postura perfecta para los hombres que quieren relajarse y divertirse, por lo que evidentemente hay que tener en cuenta esta posición. El hombre se tumba de espaldas y dobla ligeramente una pierna por la rodilla. La pareja femenina se sienta sobre el pene de forma que sus piernas queden en un lado junto a la pierna doblada de su pareja masculina, que la pareja femenina coge con la mano por la rodilla y la otra mano la pone en el pecho del hombre. La pareja masculina pone su brazo en el cuello de la mujer y toma su rodilla por la otra. La mujer se desplaza en esta posición.",
    "static/images/acuario.png": "Posición sexual  ACUARIO: Cuerpos desnudos y pensamientos se anudan, están en la misma posición, pero cada pareja desempeña su papel personal. La mujer se tumba abriendo las piernas, y el hombre se coloca entre ellas de rodillas para levantar a la compañera por la cintura, de modo que sólo la cabeza y el antebrazo puedan ser su apoyo. La mujer lanza sus piernas a los muslos del hombre, doblándolas por las rodillas, apoya sus nalgas con los brazos, ayudando a la pareja masculina a mantener el ritmo del sexo. En esta posición ambos miembros de la pareja tienen las manos ocupadas, pero tienen los ojos para mirarse y a veces eso es más que suficiente.",
    "static/images/circulo.png": "Posición sexual  CIRCULO: Aquí tienes una posición picante que simplifica mucho el sexo oral, además de hacerlo mucho más sofisticado y variado. El hombre y la mujer se acuestan de lado para que sus caras estén a la altura de las zonas íntimas del otro y sus piernas estén ligeramente dobladas por las rodillas. El hombre toma la pierna de su amante con una mano y la levanta, accediendo a la entrepierna de su compañera, acariciando sus nalgas con la segunda mano. La mujer tiene la capacidad de estimular el pene de su pareja masculina con sus manos, de acariciar sus testículos, nalgas y muslos, todo depende de su experiencia e imaginación. Esta es una posición definitivamente buena.",
    "static/images/cascada.png":"Posición sexual  CASCADA: Un cóctel de caricias suaves, besos apasionados, ojos ardientes y deseos insatisfechos, hay que beberlo juntos, en esta posición, y hasta la última gota. El hombre cesa de rodillas, las piernas se separan, la espalda está recta. La mujer con sus piernas abraza las nalgas de su pareja masculina, los pies se apilan en cruz, cara a cara. El hombre con sus manos toma la cintura de su querida, ella está totalmente inclinada hacia atrás, tirando de las manos, sujetándolas, y está en la posición de medio puente. La pareja masculina realiza movimientos y la mantiene en esta posición",
    "static/images/basset hound.png": "Posición sexual  BASSET HOUND: Desde el primer toque hasta el último empujón tu cuerpo debe arder de deseo, esta posición es sólo un camino hacia el placer, y lo delicioso que será tu sexo, depende de tu actitud. La mujer se pone a cuatro patas, los pies juntos, las manos a la altura de los hombros, apoyadas en las palmas, la espalda ligeramente arqueada, la cabeza echada hacia atrás. El hombre se pone de rodillas detrás de su compañera de tal manera, que sus piernas están entre los pies de ella, una mano la pone en la cintura, con la otra coge el capullo de su querida y la empuja al ritmo de sus movimientos.",
    "static/images/tornado.png":"Posición sexual  TORNADO: Haga girar a su pareja en un torbellino de emociones brillantes, llévelo a la dicha con una culminación imprevisible, drene todo su cuerpo y a cambio, usted obtendrá mucho más. La mujer se tumba de espaldas, con los brazos y las piernas abiertos hacia los lados y una pierna doblada en la rodilla. La pareja masculina se tumba encima de la dama un poco oblicuamente, de modo que sus piernas abiertas y rectas quedan debajo de la pierna doblada de su querida. El hombre mantiene la parte superior de su cuerpo en la longitud del brazo recto, penetra en su dama de lado, es una posición muy singular, pruébala en la práctica.",
    "static/images/culumpio.png":"Posición sexual  CULUMPIO: Subiendo y bajando, como si su cuerpo flotara ingrávido, la sensación del tacto caliente de las manos y un calor ardiente de placer que penetra en los cuerpos de los compañeros no devuelven a la realidad. El hombre se tumba de espaldas y abre las piernas. La mujer se sienta sobre el pene, ligeramente inclinada hacia atrás, se apoya en las manos separadas junto a los antebrazos del hombre. Ella dobla las rodillas y lanza una pierna sobre la otra, de modo que la pierna derecha queda en caída libre. La pareja masculina toma a su amante por las nalgas y la ayuda a moverse, al mismo tiempo que puede observar el proceso.",
    "static/images/inquisidor.png":"Posición sexual  INQUISIDOR: Esta posición tiene merecidamente este nombre fatídico, porque la mujer está en poder de un hombre de corazón y es él quien decide cuándo se acaba esta lucha. La mujer se tumba cómodamente de espaldas, abre las piernas y dobla ligeramente las rodillas. La pareja masculina se sitúa entre las piernas de ella tumbada sobre su vientre, sus piernas también están dobladas por las rodillas y están levantadas, sujeta las nalgas de su amante con sus brazos, y en cuanto al resto, todo depende del vuelo de su imaginación. El hombre puede atormentar a su tentadora en esa posición durante mucho tiempo, sin permitirle sentir un orgasmo o actuar con más decisión y claridad, llevándola deliberadamente al éxtasis.",
    "static/images/pared.png":"Posición sexual  PARED: Si te gusta el sexo en lugares picantes o inusuales, entonces pon esta posición sobre aviso y busca algo en lo que apoyarte. El hombre se coloca de espaldas a la pared, colocando las piernas ligeramente hacia delante y abriéndolas un poco. La mujer se coloca al lado, de espaldas a la elegida, inclinándose ligeramente hacia delante. Los talones de ella deben estar situados cerca de los del hombre, y sus manos están sobre los muslos de él. La pareja masculina la sujeta por la cintura y mueve sus muslos con más frecuencia y rapidez. Esta posición puede ser buena en cualquier habitación de su casa, incluso para el sexo en clubes y otros lugares igualmente interesantes. Si nunca has probado el sexo en el ascensor, entonces, aquí tienes una oportunidad única para ello",
    "static/images/encuadernacion.png":"Posición sexual  ENCUADERNACION: Los cuerpos están en estrecho contacto el uno con el otro, y aún más desnudos prometen a ambos miembros de la pareja un mar de ternura y placer, tener sexo y acariciarse es la forma más elevada de placer. La mujer se tumba de lado con las piernas ligeramente flexionadas por las rodillas y las separa ampliamente. El hombre se tumba de lado detrás de su compañera, pone una pierna sobre la cadera de ella y penetra a su amante por la espalda. Con su mano el hombre acaricia el pecho de su mujer, con la segunda mano mantiene la cabeza levantada y puede estar besando el cuello de su pareja. La mujer pone su mano en el muslo de él y lo acaricia suavemente.",
    "static/images/jinete.png":"Posición sexual  JINETE: Es imposible controlar la situación, cuando el papel de jinete lo desempeña una seductora pareja femenina, todo el poder está en manos de la mujer y el ritmo frenético lleva a una pareja al clímax ardiente. El hombre apoya la cabeza en la almohada y estira las piernas por delante; la mujer cabalga sobre el pene, manteniéndose en ancas. Para un mayor equilibrio, ella pone las manos en el pecho del hombre, haciendo un poco de apoyo. La pareja masculina sujeta a su amante por las piernas, pero también puede sentir su pecho agitado, acariciar el cuerpo o simplemente mirar. Él recibirá una satisfacción no menor, ¡eso es seguro!"
    # Agrega más imágenes y descripciones aquí
}

@app.route('/')
def index():
    # Elige una imagen aleatoria y su descripción
    random_image_path, random_description = random.choice(list(image_descriptions.items()))
    return render_template('index.html', description=random_description, image_path=random_image_path)

@app.route('/nueva_imagen')
def nueva_imagen():
    # Obtiene una nueva imagen aleatoria y su descripción
    random_image_path, random_description = random.choice(list(image_descriptions.items()))
    return jsonify({'image_path': random_image_path, 'description': random_description})





if __name__ == '__main__':
    app.run(debug=True)
